PROJECT = part06_3

SRCFILES = reset.asm init.asm text_lcd.asm utils.asm int_vect.asm debug_int.asm buttons.asm pic8259.asm pit8254.asm
SRCFILES += main.c cpu_state.c

LDSCRIPT = ../../bare8086.ld

include ../../build8086.mk
