PROJECT = part07

SRCFILES = reset.asm init.asm periph186.asm text_lcd.asm utils.asm int_vect.asm debug_int.asm buttons.asm system.asm
SRCFILES += main.c cpu_state.c

LDSCRIPT = ../bare8086.ld

include ../build8086.mk
